resources:
  pipelines:
    telco_churn:
      name: "Telco Churn - Bronze + Silver"
      target: default
      catalog: workspace
      serverless: true
      development: true
      continuous: false
      libraries:
        - file:
            path: ./01_bronze_ingestion.py
        - file:
            path: ./02_silver_transformation.py
        - file:
            path: ../rules/__init__.py
        - file:
            path: ../rules/customers.py