resources:
  pipelines:
    telco_churn_bronze:
      name: "Telco Churn - Bronze Silver Layer"
      target: default
      catalog: workspace

      libraries:
        - file:
            path: ./01_bronze_ingestion.py
        - file:
            path: ./02_silver_transformation.py

      serverless: true

      development: true
      continuous: false