resources:
  pipelines:
    telco_churn:
      name: "Telco Churn - Bronze + Silver"
      target: default
      catalog: workspace
      serverless: true
      development: true
      continuous: false
      libraries:
        - file:
            path: ./src/medallion_pipeline/transformations/01_bronze_ingestion.py
        - file:
            path: ./src/medallion_pipeline/transformations/02_silver_transformation.py
        - file:
            path: ./src/medallion_pipeline/rules/__init__.py
        - file:
            path: ./src/medallion_pipeline/rules/customers.py